### ISSUE TITLE
Harmonize properties files management

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2496]
I create a dedicated issue to keep track of the work to harmonize the management of properties files in the geOrchestra modules.

The work to be done:
- remove the "resources" properties files like [mapfishapp.properties](https://github.com/georchestra/georchestra/blob/18.12/mapfishapp/src/main/resources/mapfishapp.properties)
- ensure both `default.properties` and the application-specific properties file from the [datadir](https://github.com/georchestra/datadir) are accessed by `<context:property-placeholder>`
- replace the use of GeorchestraConfiguration's [`getProperty`](https://github.com/georchestra/georchestra/blob/c8fcd26e4b932267effac04897aca86b44d4ad3e/commons/src/main/java/org/georchestra/commons/configuration/GeorchestraConfiguration.java#L132) method by a property passed to a bean using a Spring placeholder (see [spring-context.xsd](http://www.springframework.org/schema/context/spring-context.xsd)).
- set a default value to every Spring placeholder.
- ensure all the parameters used in the Spring configuration files are defined in the datadir's properties files (eg, the following is not defined in the datadir)

    https://github.com/georchestra/georchestra/blob/c8fcd26e4b932267effac04897aca86b44d4ad3e/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L71

Modules processed:

- [x] mapfishapp - #2497 and https://github.com/georchestra/datadir/pull/130
- [x] extractorapp - #2498 and https://github.com/georchestra/datadir/pull/131, also #2505
- [x] header - #2503
- [x] console - #2508, https://github.com/georchestra/datadir/pull/133
- [x] atlas - # 2509 and https://github.com/georchestra/datadir/pull/134
- [x] security-proxy - #2510 and https://github.com/georchestra/datadir/pull/135
- [x] cas - #2512
- [x] geoserver - nothing to do
- [x] geonetwork - nothing to do - but see https://github.com/georchestra/georchestra/issues/2379#issuecomment-465998817
- [x] geowebcache - review #2525 
- [x] analytics - #2500 and https://github.com/georchestra/datadir/pull/132, blocked by #2507 - review #2526 and [georchestra/datadir#136](https://github.com/georchestra/datadir/pull/136)

See also:

- [x] comment all the properties in the datadir and add the corresponding comments to explain what the properties are for - https://github.com/georchestra/datadir/issues/129 - review https://github.com/georchestra/datadir/pull/138
- [x] use plaeholders in the datadir properties files - https://github.com/georchestra/datadir/issues/126 - review https://github.com/georchestra/datadir/pull/137

Finally:

- [x] remove the [`getProperty`](https://github.com/georchestra/georchestra/blob/c8fcd26e4b932267effac04897aca86b44d4ad3e/commons/src/main/java/org/georchestra/commons/configuration/GeorchestraConfiguration.java#L132) method and all the code related to properties from the [commons module](https://github.com/georchestra/georchestra/tree/18.12/commons) -  blocked by #2507 - review #2531

And optionally:

- [ ] remove instances of `loadCustomPropertiesFile` method? But see https://github.com/georchestra/georchestra/blob/088030f596b1057a14c406ae3b30604da4f97d1f/security-proxy/src/main/java/org/georchestra/security/BasicAuthChallengeByUserAgent.java#L71-L73
- [ ] for every module, ensure all the parameters that could be configured have a corresponding property in datadir (eg, the following could be configurable)

    https://github.com/georchestra/georchestra/blob/c8fcd26e4b932267effac04897aca86b44d4ad3e/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L27

    https://github.com/georchestra/georchestra/blob/c8fcd26e4b932267effac04897aca86b44d4ad3e/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L50

**Comment by fvanderbiest** [comment]
> * comment all the properties in the datadir

Not sure about it.

**Comment by severo** [comment]
> Not sure about it.

OK, let discuss about it in https://github.com/georchestra/datadir/issues/129, and I will update here depending on what we define.

**Comment by severo** [comment]
What do you think about the two last optional steps? I propose to close here.
